[supervisord]
nodaemon=true
user=root

# [program:beyla]
# user=root
# command=beyla -config /etc/beyla/config.yaml

[program:alloy]
command=alloy run /etc/alloy/config.alloy
autostart=true
autorestart=true

[program:node]
command=node index.js
autostart=true
autorestart=true
