[supervisord]
nodaemon=true

[program:alloy]
command=alloy daemon --config /etc/alloy/config.alloy
autostart=true
autorestart=true

[program:node]
command=node index.js
autostart=true
autorestart=true
