[supervisord]
nodaemon=true
user=root

[program:beyla]
command=beyla -config /etc/alloy/config.yml

[program:alloy]
command=alloy run /etc/alloy/config.alloy
autostart=true
autorestart=true

[program:node]
command=node index.js
autostart=true
autorestart=true
